// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-09-19 18:55:14.0647931 +0800 CST m=+0.109998501

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "纸喵软件系列之服务端",
        "title": "纸喵 qiansi API",
        "termsOfService": "http://zhimiao.org",
        "contact": {
            "name": "API Support",
            "url": "http://tools.zhimiao.org",
            "email": "mail@xiaoliu.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:1315",
    "basePath": "/",
    "paths": {
        "/admin/DeployDel": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除部署应用",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployDelParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"操作成功\",\"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/DeployDo": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "启动部署",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployDoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"启动成功\",\"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/DeployLists": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取部署应用列表",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resp.DeployVO"
                            }
                        }
                    }
                }
            }
        },
        "/admin/DeployLog": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取部署日志",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployLogParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resp.DeployLogVO"
                            }
                        }
                    }
                }
            }
        },
        "/admin/DeployRelationServer": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "部署应用关联服务器",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployRelationParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"关联成功\",\"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/DeployRunLog": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取当前部署应用指定服务器的运行日志",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployRunLogParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.DeployLog"
                        }
                    }
                }
            }
        },
        "/admin/DeployRunLogTab": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取当前部署应用绑定的服务器列表，用于渲染运行日志选项卡",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployServerParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resp.DeployRunLogTabVO"
                            }
                        }
                    }
                }
            }
        },
        "/admin/DeployServer": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取当前部署应用的服务器列表",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeployServerParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Server"
                        }
                    }
                }
            }
        },
        "/admin/DeploySet": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "设置部署应用",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.DeploySetParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"操作成功\",\"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/ScheduleCreate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "创建计划任务",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ScheduleCreateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/ScheduleDel": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "执行计划任务",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ScheduleDoParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除计划任务",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ScheduleDelParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/ScheduleLists": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取计划任务列表",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ScheduleListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.PageInfo"
                        }
                    }
                }
            }
        },
        "/admin/ServerDel": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除服务器",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ServerDelParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"操作成功\",\"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/ServerLists": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取服务器(客户端)列表",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ServerListParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resp.ServerVO"
                            }
                        }
                    }
                }
            }
        },
        "/admin/ServerSet": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "设置服务器信息",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.ServerSetParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"操作成功\",\"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/UserResetPwd": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.UserResetPwdParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"修改成功\", \"data\": null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/UserSigin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.UserSiginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"登录成功\", \"data\": {\"CreateTime\": \"2019-02-27T16:11:27+08:00\",\"InviterUid\": 0,\"Password\": \"\",\"Phone\": \"15061370322\",\"Status\": 1,\"Uid\": 2, \"UpdateTime\": \"2019-02-27T16:19:54+08:00\", \"Token\":\"sdfsdafsd..\"}}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/UserSiginUp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "注册账号",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.UserSiginUpParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"注册成功\",\"data\": {\"CreateTime\": \"2019-02-27T16:11:27+08:00\",\"InviterUid\": 0,\"Password\": \"\",\"Phone\": \"15061370322\",\"Status\": 1,\"Uid\": 2, \"UpdateTime\": \"2019-02-27T16:19:54+08:00\", \"Token\":\"sdfsdafsd..\"}}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.UserInfoVO"
                        }
                    }
                }
            }
        },
        "/admin/VerifyByImg": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取图片验证码",
                "responses": {
                    "200": {
                        "description": "{\"code\":1,\"msg\":\"\",\"data\":{\"idkey\":\"ckFbFAcMo7sy7qGyonAd\",\"img\":\"data:image/png;base64,iVBORw0...\"}}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/admin/VerifyBySMS": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取短信验证码",
                "parameters": [
                    {
                        "description": "入参集合",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/req.VerifyBySMSParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":1,\"msg\":\"发送成功\",\"data\":null}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/clinet/ApiDeployLog": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "客户端日志推送",
                "parameters": [
                    {
                        "type": "string",
                        "description": "部署应用ID",
                        "name": "deployId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "部署版本号",
                        "name": "version",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日志文本内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/clinet/ApiDeployNotify": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "客户端部署成功回调",
                "parameters": [
                    {
                        "type": "string",
                        "description": "版本号",
                        "name": "version",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "部署应用ID",
                        "name": "deploy_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/clinet/ApiGetDeployTask": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取服务器部署任务清单",
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"读取成功\",\"data\": [deploy]}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        },
        "/clinet/ApiRegServer": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "服务器注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户UID",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端设备号",
                        "name": "device",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 1,\"msg\": \"登录成功\", \"data\": {\"CreateTime\": \"2019-02-27T16:11:27+08:00\",\"InviterUid\": 0,\"Password\": \"\",\"Phone\": \"15061370322\",\"Status\": 1,\"Uid\": 2, \"UpdateTime\": \"2019-02-27T16:19:54+08:00\", \"Token\":\"sdfsdafsd..\"}}",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/resp.ApiResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DeployLog": {
            "type": "object",
            "properties": {
                "clientIp": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deployId": {
                    "type": "integer"
                },
                "deployVersion": {
                    "type": "integer"
                },
                "deviceId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "serverId": {
                    "type": "integer"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "models.Server": {
            "type": "object",
            "properties": {
                "apiSecret": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deviceId": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "serverName": {
                    "type": "string"
                },
                "serverRuleId": {
                    "type": "integer"
                },
                "serverStatus": {
                    "type": "integer"
                },
                "uid": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        },
        "req.DeployDelParam": {
            "type": "object",
            "properties": {
                "deployId": {
                    "description": "部署应用ID",
                    "type": "integer"
                }
            }
        },
        "req.DeployDoParam": {
            "type": "object",
            "properties": {
                "deployId": {
                    "description": "部署应用ID",
                    "type": "integer"
                }
            }
        },
        "req.DeployListParam": {
            "type": "object",
            "properties": {
                "lastId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "req.DeployLogParam": {
            "type": "object",
            "properties": {
                "deployId": {
                    "description": "应用ID",
                    "type": "integer"
                },
                "deployVersion": {
                    "description": "版本",
                    "type": "integer"
                },
                "endTime": {
                    "description": "结束时间",
                    "type": "string"
                },
                "lastId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "serverId": {
                    "description": "服务器",
                    "type": "integer"
                },
                "startTime": {
                    "description": "开始时间",
                    "type": "string"
                }
            }
        },
        "req.DeployRelationParam": {
            "type": "object",
            "properties": {
                "deployId": {
                    "description": "部署应用ID",
                    "type": "integer"
                },
                "relation": {
                    "description": "关联操作 true-关联 false-取消",
                    "type": "boolean"
                },
                "serverId": {
                    "description": "服务器ID",
                    "type": "integer"
                }
            }
        },
        "req.DeployRunLogParam": {
            "type": "object",
            "properties": {
                "deployId": {
                    "description": "部署应用ID",
                    "type": "integer"
                },
                "serverId": {
                    "description": "服务器ID",
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "req.DeployServerParam": {
            "type": "object",
            "properties": {
                "deployId": {
                    "description": "部署应用ID",
                    "type": "integer"
                }
            }
        },
        "req.DeploySetParam": {
            "type": "object",
            "properties": {
                "afterCommand": {
                    "description": "后置命令",
                    "type": "string"
                },
                "beforeCommand": {
                    "description": "前置命令",
                    "type": "string"
                },
                "branch": {
                    "description": "git分支",
                    "type": "string"
                },
                "deployKeys": {
                    "description": "部署私钥",
                    "type": "string"
                },
                "deployType": {
                    "description": "部署类型 0-本地 1-git 2-zip",
                    "type": "integer"
                },
                "id": {
                    "description": "应用唯一编号",
                    "type": "integer"
                },
                "localPath": {
                    "description": "本地部署地址",
                    "type": "string"
                },
                "remoteUrl": {
                    "description": "资源地址",
                    "type": "string"
                },
                "title": {
                    "description": "应用名称",
                    "type": "string"
                }
            }
        },
        "req.ScheduleCreateParam": {
            "type": "object",
            "properties": {
                "command": {
                    "description": "执行命令",
                    "type": "string"
                },
                "crontab": {
                    "description": "表达式",
                    "type": "string"
                },
                "remain": {
                    "description": "执行次数-1-无限",
                    "type": "integer"
                },
                "scheduleType": {
                    "description": "1-http 2-shell",
                    "type": "integer"
                },
                "serverId": {
                    "description": "执行服务器ID，云服务器id为0",
                    "type": "integer"
                },
                "timeout": {
                    "description": "执行超时时间",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "req.ScheduleDelParam": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "req.ScheduleDoParam": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "req.ScheduleListParam": {
            "type": "object",
            "properties": {
                "lastId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "req.ServerDelParam": {
            "type": "object",
            "properties": {
                "serverId": {
                    "type": "integer"
                }
            }
        },
        "req.ServerListParam": {
            "type": "object",
            "properties": {
                "lastId": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "serverName": {
                    "type": "string"
                }
            }
        },
        "req.ServerSetParam": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "serverName": {
                    "description": "服务器备注名",
                    "type": "string"
                },
                "serverRuleId": {
                    "description": "服务器规则id",
                    "type": "integer"
                },
                "serverStatus": {
                    "description": "服务器状态 -1-失效 0-待认领 1-已分配通信密钥 2-已绑定",
                    "type": "integer"
                }
            }
        },
        "req.UserResetPwdParam": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "req.UserSiginParam": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "req.UserSiginUpParam": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "短信验证码",
                    "type": "string"
                },
                "inviterUid": {
                    "description": "邀请人",
                    "type": "integer"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "req.VerifyBySMSParam": {
            "type": "object",
            "properties": {
                "imgCode": {
                    "description": "验证码code",
                    "type": "string"
                },
                "imgIdKey": {
                    "description": "图片验证码id",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "resp.ApiResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "resp.DeployLogVO": {
            "type": "object",
            "properties": {
                "clientIp": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deployId": {
                    "type": "integer"
                },
                "deployVersion": {
                    "type": "integer"
                },
                "deviceId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "serverId": {
                    "type": "integer"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "resp.DeployRunLogTabVO": {
            "type": "object",
            "properties": {
                "deployVersion": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "serverName": {
                    "type": "string"
                }
            }
        },
        "resp.DeployVO": {
            "type": "object",
            "properties": {
                "afterCommand": {
                    "type": "string"
                },
                "beforeCommand": {
                    "type": "string"
                },
                "branch": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deployKeys": {
                    "type": "string"
                },
                "deployType": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "localPath": {
                    "type": "string"
                },
                "nowVersion": {
                    "type": "integer"
                },
                "remoteUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        },
        "resp.PageInfo": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "rows": {
                    "type": "object"
                },
                "totalSize": {
                    "type": "integer"
                }
            }
        },
        "resp.ServerVO": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "deviceId": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "serverName": {
                    "type": "string"
                },
                "serverRuleId": {
                    "type": "integer"
                },
                "serverStatus": {
                    "type": "integer"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        },
        "resp.UserInfoVO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
