definitions:
  models.ApiResult:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  models.Server:
    properties:
      apiSecret:
        type: string
      createTime:
        type: string
      deviceId:
        type: string
      domain:
        type: string
      id:
        type: integer
      serverName:
        type: string
      serverRuleId:
        type: integer
      serverStatus:
        type: integer
      uid:
        type: integer
      updateTime:
        type: string
    type: object
  zreq.DeployDelParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
    type: object
  zreq.DeployDoParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
    type: object
  zreq.DeployRelationParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
      relation:
        description: 关联操作 true-关联 false-取消
        type: boolean
      serverId:
        description: 服务器ID
        type: integer
    type: object
  zreq.DeploySetParam:
    properties:
      afterCommand:
        description: 后置命令
        type: string
      beforeCommand:
        description: 前置命令
        type: string
      branch:
        description: git分支
        type: string
      deployKeys:
        description: 部署私钥
        type: string
      deployType:
        description: 部署类型 0-本地 1-git 2-zip
        type: integer
      id:
        description: 应用唯一编号
        type: integer
      localPath:
        description: 本地部署地址
        type: string
      remoteUrl:
        description: 资源地址
        type: string
      title:
        description: 应用名称
        type: string
    type: object
  zreq.ServerDelParam:
    properties:
      serverId:
        type: integer
    type: object
  zreq.UserResetPwdParam:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  zreq.UserSiginParam:
    properties:
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  zreq.UserSiginUpParam:
    properties:
      code:
        description: 短信验证码
        type: string
      inviterUid:
        description: 邀请人
        type: integer
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  zreq.VerifyBySMSParam:
    properties:
      imgCode:
        description: 验证码code
        type: string
      imgIdKey:
        description: 图片验证码id
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  zresp.UserInfoVO:
    properties:
      token:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: mail@xiaoliu.org
    name: API Support
    url: http://tools.zhimiao.org
  description: 纸喵软件系列之服务端
  license: {}
  termsOfService: http://zhimiao.org
  title: 纸喵 qiansi API
  version: "1.0"
paths:
  /admin/DeployDel:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.DeployDelParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 删除部署应用
  /admin/DeployDo:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.DeployDoParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "启动成功","data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: '启动部署 TODO: 后期关闭此接口的开放特性，新增外部接口，通过不可枚举key作为部署参数'
  /admin/DeployLists:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "读取成功","data": [{"AfterCommand": "324545","BeforeCommand":
            "1232132132","Branch": "123213","CreateTime": "2019-02-28T10:24:41+08:00","DeployType":
            1,"Id": 491,"LocalPath": "123213","NowVersion": 0,"RemoteUrl": "123213","Title":
            "491-一号机器的修改241","Uid": 2,"UpdateTime": "2019-02-28T10:25:17+08:00"}]}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 获取部署应用列表
  /admin/DeployRelationServer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.DeployRelationParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "关联成功","data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 部署应用关联服务器
  /admin/DeployServer:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            $ref: '#/definitions/models.Server'
            type: object
      summary: 获取当前部署应用的服务器列表
  /admin/DeploySet:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.DeploySetParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 设置部署应用
  /admin/ServerDel:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.ServerDelParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 删除服务器
  /admin/ServerLists:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "读取成功","data": [{"CreateTime": "2019-03-02T16:10:10+08:00","DeviceId":
            "","Domain": "127.0.0.1","Id": 1,"ServerName": "纸喵5号机","ServerRuleId":
            0,"ServerStatus": 0,"Uid": 2,"UpdateTime": "2019-05-22T17:40:18+08:00"}]}'
          schema:
            $ref: '#/definitions/models.Server'
            type: object
      summary: 获取服务器(客户端)列表
  /admin/ServerSet:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.DeploySetParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 设置服务器信息
  /admin/UserResetPwd:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.UserResetPwdParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "修改成功", "data": null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 修改密码
  /admin/UserSigin:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.UserSiginParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "登录成功", "data": {"CreateTime": "2019-02-27T16:11:27+08:00","InviterUid":
            0,"Password": "","Phone": "15061370322","Status": 1,"Uid": 2, "UpdateTime":
            "2019-02-27T16:19:54+08:00", "Token":"sdfsdafsd.."}}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 登录
  /admin/UserSiginUp:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.UserSiginUpParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "注册成功","data": {"CreateTime": "2019-02-27T16:11:27+08:00","InviterUid":
            0,"Password": "","Phone": "15061370322","Status": 1,"Uid": 2, "UpdateTime":
            "2019-02-27T16:19:54+08:00", "Token":"sdfsdafsd.."}}'
          schema:
            $ref: '#/definitions/zresp.UserInfoVO'
            type: object
      summary: 注册账号
  /admin/VerifyByImg:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"","data":{"idkey":"ckFbFAcMo7sy7qGyonAd","img":"data:image/png;base64,iVBORw0..."}}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 获取图片验证码
  /admin/VerifyBySMS:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/zreq.VerifyBySMSParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"发送成功","data":null}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 获取短信验证码
  /clinet/ApiDeployNotify:
    get:
      consumes:
      - application/json
      parameters:
      - description: 版本号
        in: query
        name: version
        required: true
        type: string
      - description: 部署应用ID
        in: query
        name: deploy_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 客户端部署成功回调
  /clinet/ApiGetDeployTask:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "读取成功","data": [deploy]}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 获取服务器部署任务清单
  /clinet/ApiRegServer:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户UID
        in: query
        name: uid
        required: true
        type: string
      - description: 客户端设备号
        in: query
        name: device
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "登录成功", "data": {"CreateTime": "2019-02-27T16:11:27+08:00","InviterUid":
            0,"Password": "","Phone": "15061370322","Status": 1,"Uid": 2, "UpdateTime":
            "2019-02-27T16:19:54+08:00", "Token":"sdfsdafsd.."}}'
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 服务器注册
  /clinet/LogPush:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 客户端平台编号
        in: formData
        name: server_id
        required: true
        type: string
      - description: 客户端设备号
        in: formData
        name: device
        required: true
        type: string
      - description: 日志文本内容
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiResult'
            type: object
      summary: 客户端日志推送
swagger: "2.0"
