basePath: /
definitions:
  models.DeployLog:
    properties:
      clientIp:
        type: string
      content:
        type: string
      createTime:
        type: string
      deployId:
        type: integer
      deployVersion:
        type: integer
      deviceId:
        type: string
      id:
        type: integer
      serverId:
        type: integer
      uid:
        type: integer
    type: object
  models.Server:
    properties:
      apiSecret:
        type: string
      createTime:
        type: string
      deviceId:
        type: string
      domain:
        type: string
      id:
        type: integer
      serverName:
        type: string
      serverRuleId:
        type: integer
      serverStatus:
        type: integer
      uid:
        type: integer
      updateTime:
        type: string
    type: object
  req.DeployDelParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
    type: object
  req.DeployDoParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
    type: object
  req.DeployListParam:
    properties:
      lastId:
        type: integer
      page:
        type: integer
      pageSize:
        type: integer
      title:
        type: string
    type: object
  req.DeployLogParam:
    properties:
      deployId:
        description: 应用ID
        type: integer
      deployVersion:
        description: 版本
        type: integer
      endTime:
        description: 结束时间
        type: string
      lastId:
        type: integer
      page:
        type: integer
      pageSize:
        type: integer
      serverId:
        description: 服务器
        type: integer
      startTime:
        description: 开始时间
        type: string
    type: object
  req.DeployRelationParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
      relation:
        description: 关联操作 true-关联 false-取消
        type: boolean
      serverId:
        description: 服务器ID
        type: integer
    type: object
  req.DeployRunLogParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
      serverId:
        description: 服务器ID
        type: integer
      version:
        type: integer
    type: object
  req.DeployServerParam:
    properties:
      deployId:
        description: 部署应用ID
        type: integer
    type: object
  req.DeploySetParam:
    properties:
      afterCommand:
        description: 后置命令
        type: string
      beforeCommand:
        description: 前置命令
        type: string
      branch:
        description: git分支
        type: string
      deployKeys:
        description: 部署私钥
        type: string
      deployType:
        description: 部署类型 0-本地 1-git 2-zip
        type: integer
      id:
        description: 应用唯一编号
        type: integer
      localPath:
        description: 本地部署地址
        type: string
      remoteUrl:
        description: 资源地址
        type: string
      title:
        description: 应用名称
        type: string
    type: object
  req.PageParam:
    properties:
      lastId:
        type: integer
      page:
        type: integer
      pageSize:
        type: integer
    type: object
  req.ServerDelParam:
    properties:
      serverId:
        type: integer
    type: object
  req.ServerListParam:
    properties:
      lastId:
        type: integer
      page:
        type: integer
      pageSize:
        type: integer
      serverName:
        type: string
    type: object
  req.ServerSetParam:
    properties:
      id:
        type: integer
      serverName:
        description: 服务器备注名
        type: string
      serverRuleId:
        description: 服务器规则id
        type: integer
      serverStatus:
        description: 服务器状态 -1-失效 0-待认领 1-已分配通信密钥 2-已绑定
        type: integer
    type: object
  req.UserResetPwdParam:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  req.UserSiginParam:
    properties:
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  req.UserSiginUpParam:
    properties:
      code:
        description: 短信验证码
        type: string
      inviterUid:
        description: 邀请人
        type: integer
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  req.VerifyBySMSParam:
    properties:
      imgCode:
        description: 验证码code
        type: string
      imgIdKey:
        description: 图片验证码id
        type: string
      phone:
        description: 手机号
        type: string
    type: object
  resp.ApiResult:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  resp.DeployLogVO:
    properties:
      clientIp:
        type: string
      content:
        type: string
      createTime:
        type: string
      deployId:
        type: integer
      deployVersion:
        type: integer
      deviceId:
        type: string
      id:
        type: integer
      serverId:
        type: integer
      uid:
        type: integer
    type: object
  resp.DeployRunLogTabVO:
    properties:
      deployVersion:
        type: integer
      id:
        type: integer
      serverName:
        type: string
    type: object
  resp.DeployVO:
    properties:
      afterCommand:
        type: string
      beforeCommand:
        type: string
      branch:
        type: string
      createTime:
        type: string
      deployKeys:
        type: string
      deployType:
        type: integer
      id:
        type: integer
      localPath:
        type: string
      nowVersion:
        type: integer
      remoteUrl:
        type: string
      title:
        type: string
      uid:
        type: integer
      updateTime:
        type: string
    type: object
  resp.PageInfo:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      rows:
        type: object
      totalSize:
        type: integer
    type: object
  resp.ServerVO:
    properties:
      createTime:
        type: string
      deviceId:
        type: string
      domain:
        type: string
      id:
        type: integer
      serverName:
        type: string
      serverRuleId:
        type: integer
      serverStatus:
        type: integer
      updateTime:
        type: string
    type: object
  resp.UserInfoVO:
    properties:
      token:
        type: string
    type: object
host: localhost:1315
info:
  contact:
    email: mail@xiaoliu.org
    name: API Support
    url: http://tools.zhimiao.org
  description: 纸喵软件系列之服务端
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://zhimiao.org
  title: 纸喵 qiansi API
  version: "1.0"
paths:
  /admin/DeployDel:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployDelParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 删除部署应用
  /admin/DeployDo:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployDoParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "启动成功","data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 启动部署
  /admin/DeployLists:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployListParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/resp.DeployVO'
            type: array
      summary: 获取部署应用列表
  /admin/DeployLog:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployLogParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            items:
              $ref: '#/definitions/resp.DeployLogVO'
            type: array
      summary: 获取部署日志
  /admin/DeployRelationServer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployRelationParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "关联成功","data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 部署应用关联服务器
  /admin/DeployRunLog:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployRunLogParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            $ref: '#/definitions/models.DeployLog'
            type: object
      summary: 获取当前部署应用指定服务器的运行日志
  /admin/DeployRunLogTab:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployServerParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            items:
              $ref: '#/definitions/resp.DeployRunLogTabVO'
            type: array
      summary: 获取当前部署应用绑定的服务器列表，用于渲染运行日志选项卡
  /admin/DeployServer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeployServerParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 返回
          schema:
            $ref: '#/definitions/models.Server'
            type: object
      summary: 获取当前部署应用的服务器列表
  /admin/DeploySet:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.DeploySetParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 设置部署应用
  /admin/ScheduleLists:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.PageParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.PageInfo'
            type: object
      summary: 获取计划任务列表
  /admin/ServerDel:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ServerDelParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 删除服务器
  /admin/ServerLists:
    get:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ServerListParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/resp.ServerVO'
            type: array
      summary: 获取服务器(客户端)列表
  /admin/ServerSet:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ServerSetParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "操作成功","data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 设置服务器信息
  /admin/UserResetPwd:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserResetPwdParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "修改成功", "data": null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 修改密码
  /admin/UserSigin:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserSiginParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "登录成功", "data": {"CreateTime": "2019-02-27T16:11:27+08:00","InviterUid":
            0,"Password": "","Phone": "15061370322","Status": 1,"Uid": 2, "UpdateTime":
            "2019-02-27T16:19:54+08:00", "Token":"sdfsdafsd.."}}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 登录
  /admin/UserSiginUp:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserSiginUpParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "注册成功","data": {"CreateTime": "2019-02-27T16:11:27+08:00","InviterUid":
            0,"Password": "","Phone": "15061370322","Status": 1,"Uid": 2, "UpdateTime":
            "2019-02-27T16:19:54+08:00", "Token":"sdfsdafsd.."}}'
          schema:
            $ref: '#/definitions/resp.UserInfoVO'
            type: object
      summary: 注册账号
  /admin/VerifyByImg:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"","data":{"idkey":"ckFbFAcMo7sy7qGyonAd","img":"data:image/png;base64,iVBORw0..."}}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 获取图片验证码
  /admin/VerifyBySMS:
    post:
      consumes:
      - application/json
      parameters:
      - description: 入参集合
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.VerifyBySMSParam'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"发送成功","data":null}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 获取短信验证码
  /clinet/ApiDeployLog:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 部署应用ID
        in: formData
        name: deployId
        required: true
        type: string
      - description: 部署版本号
        in: formData
        name: version
        required: true
        type: string
      - description: 日志文本内容
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 客户端日志推送
  /clinet/ApiDeployNotify:
    get:
      consumes:
      - application/json
      parameters:
      - description: 版本号
        in: query
        name: version
        required: true
        type: string
      - description: 部署应用ID
        in: query
        name: deploy_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 客户端部署成功回调
  /clinet/ApiGetDeployTask:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "读取成功","data": [deploy]}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 获取服务器部署任务清单
  /clinet/ApiRegServer:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户UID
        in: query
        name: uid
        required: true
        type: string
      - description: 客户端设备号
        in: query
        name: device
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1,"msg": "登录成功", "data": {"CreateTime": "2019-02-27T16:11:27+08:00","InviterUid":
            0,"Password": "","Phone": "15061370322","Status": 1,"Uid": 2, "UpdateTime":
            "2019-02-27T16:19:54+08:00", "Token":"sdfsdafsd.."}}'
          schema:
            $ref: '#/definitions/resp.ApiResult'
            type: object
      summary: 服务器注册
swagger: "2.0"
