definitions:
  utils.Json:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: mail@xiaoliu.org
    name: API Support
    url: http://tools.zhimiao.org
  description: 纸喵软件系列之服务端
  license: {}
  termsOfService: http://zhimiao.org
  title: 纸喵 Tools-Server API
  version: "1.0"
paths:
  /admin/user/UserSigin:
    post:
      consumes:
      - application/json
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{'
          schema:
            type: string
      summary: 登录
  /admin/verify/VerifyByImg:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"","data":{"idkey":"ckFbFAcMo7sy7qGyonAd","img":"data:image/png;base64,iVBORw0..."}}'
          schema:
            type: string
      summary: 获取图片验证码
  /admin/verify/VerifyBySMS:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 手机号
        in: formData
        name: phone
        required: true
        type: string
      - description: 图片验证码句柄
        in: formData
        name: img_idkey
        required: true
        type: string
      - description: 图片验证码
        in: formData
        name: img_code
        required: true
        type: string
      produces:
      - '*/*'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Json'
            type: object
      summary: 获取短信验证码
swagger: "2.0"
