host: localhost:8000
info:
  contact:
    email: mail@xiaoliu.org
    name: API Support
    url: http://tools.zhimiao.org
  description: 纸喵软件系列之服务端
  license: {}
  termsOfService: http://zhimiao.org
  title: 纸喵 Tools-Server API
  version: "1.0"
paths:
  /admin/verify/VerifyByImg:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,'
          schema:
            type: string
      summary: 获取图片验证码
  /admin/verify/VerifyBySMS:
    post:
      consumes:
      - application/json
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      - description: 图片验证码句柄
        in: query
        name: img_idkey
        required: true
        type: string
      - description: 图片验证码
        in: query
        name: img_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,'
          schema:
            type: string
      summary: 获取短信验证码
swagger: "2.0"
